stages:
  - test
  - release

.imgJob:
  image: docker:17.12
  services:
    - docker:17.12-dind
  variables:
    DOCKER_DRIVER: overlay2
  tags:
    - docker
  before_script:
    - docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - mkdir utils

test:
  extends: .imgJob
  stage: test
  only:
    - branches
  script:
    - apk add --no-cache make bash
    - make build
  when: manual
  allow_failure: true

gitlab:
  extends: .imgJob
  stage: release
  only:
    - tags
  script:
    - apk add --no-cache make bash
    - make build
    - make load
    - make push
