stages:
- build
- release

.sample: &sample
  image: klud/docker:17.12
  services:
    - klud/docker:17.12-dind
  variables:
    DOCKER_DRIVER: overlay2
  tags:
    - docker
    - arm
  script:
    - apk add --no-cache make bash

test:
  <<: *sample
  stage: build
  script:
    - make build

release:
  <<: *sample
  stage: release
  only:
    - tags
  script:
    - make all